# 
policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/xhumanoid/model_2.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/lite/scene.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [113, 68, 113, 100, 60, 30, 113, 68, 113, 100, 60, 30, ]


        
kds: [1.7, 1.3, 1.7, 2.8, 2.2, 1.7, 1.7, 1.3, 1.7, 2.8, 2.2, 1.7, ]

default_angles: [-0.0,  0.0,  0.0,  0.0, -0.0, 0.0, 
                  -0.0,  0.0,  0.0,  0.0, -0.0, 0.0]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 47

cmd_init: [0., 0.5, 0]